name: Build zygisk module

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: SetupNDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r24
    - name: Build
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: zygisk-module-release
        path: out/magisk-module-release.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: out/magisk-module-release.zip
